---@class Oldbook
---@field config OldbookConfig
---@field palette OldbookPalette
local Oldbook = {}

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field fg string?
---@field bg string?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class OldbookConfig
---@field terminal_colors boolean?
---@field undercurl boolean?
---@field underline boolean?
---@field bold boolean?
---@field italic ItalicConfig?
---@field strikethrough boolean?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field invert_intend_guides boolean?
---@field inverse boolean?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
Oldbook.config = {
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true,
  contrast = "",
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}

-- main oldbook color palette
---@class OldbookPalette
Oldbook.palette = {
  dark0_hard = "#262422",
  dark0 = "#3d3a37",
  dark0_soft = "#4f4b47",
  light0_hard = "#e9e2c9",
  light0 = "#e9e1c3",
  light0_soft = "#dac9aa",
  bright_red = "#7a1405",
  bright_green = "#50620f",
  bright_yellow = "#b4961a",
  bright_blue = "#366994",
  bright_purple = "#85308a",
  bright_aqua = "#158f9c",
  bright_orange = "#984e06",
  bright_brown = "#784f31",
  neutral_red = "#5e0f04",
  neutral_green = "#333f0a",
  neutral_yellow = "#957c16",
  neutral_blue = "#2a5173",
  neutral_purple = "#5f2263",
  neutral_aqua = "#0e616a",
  neutral_orange = "#983504",
  neutral_brown = "#583a24",
  gray = "#66615c",
}

-- get a hex list of oldbook colors based on current bg and constrast config
local function get_colors()
  local p = Oldbook.palette
  local config = Oldbook.config

  for color, hex in pairs(config.palette_overrides) do
    p[color] = hex
  end

  local color_groups = {
    bg0 = p.light0_hard,
    bg1 = p.light0,
    bg2 = p.light0_soft,
    fg0 = p.dark0_hard,
    fg1 = p.dark0,
    fg2 = p.dark0_soft,
    red = p.bright_red,
    green = p.bright_green,
    yellow = p.bright_yellow,
    blue = p.bright_blue,
    purple = p.bright_purple,
    aqua = p.bright_aqua,
    orange = p.bright_orange,
    brown = p.bright_brown,
    neutral_red = p.neutral_red,
    neutral_green = p.neutral_green,
    neutral_yellow = p.neutral_yellow,
    neutral_blue = p.neutral_blue,
    neutral_purple = p.neutral_purple,
    neutral_aqua = p.neutral_aqua,
    neutral_orange = p.neutral_orange,
    neutral_brown = p.neutral_brown,
    gray = p.gray,
  }

  return color_groups
end

local function get_groups()
  local colors = get_colors()
  local config = Oldbook.config

  if config.terminal_colors then
    local term_colors = {
      colors.bg0,
      colors.neutral_red,
      colors.neutral_green,
      colors.neutral_yellow,
      colors.neutral_blue,
      colors.neutral_purple,
      colors.neutral_aqua,
      colors.fg2,
      colors.gray,
      colors.red,
      colors.green,
      colors.yellow,
      colors.blue,
      colors.purple,
      colors.aqua,
      colors.fg1,
    }
    for index, value in ipairs(term_colors) do
      vim.g["terminal_color_" .. index - 1] = value
    end
  end

  local groups = {
    OldbookFg0 = { fg = colors.fg0 },
    OldbookFg1 = { fg = colors.fg1 },
    OldbookFg2 = { fg = colors.fg2 },
    OldbookGray = { fg = colors.gray },
    OldbookBg0 = { fg = colors.bg0 },
    OldbookBg1 = { fg = colors.bg1 },
    OldbookBg2 = { fg = colors.bg2 },
    OldbookRed = { fg = colors.neutral_red },
    OldbookRedBold = { fg = colors.neutral_red, bold = config.bold },
    OldbookGreen = { fg = colors.neutral_green },
    OldbookGreenBold = { fg = colors.neutral_green, bold = config.bold },
    OldbookYellow = { fg = colors.neutral_yellow },
    OldbookYellowBold = { fg = colors.neutral_yellow, bold = config.bold },
    OldbookBlue = { fg = colors.neutral_blue },
    OldbookBlueBold = { fg = colors.neutral_blue, bold = config.bold },
    OldbookPurple = { fg = colors.neutral_purple },
    OldbookPurpleBold = { fg = colors.neutral_purple, bold = config.bold },
    OldbookAqua = { fg = colors.neutral_aqua },
    OldbookAquaBold = { fg = colors.neutral_aqua, bold = config.bold },
    OldbookOrange = { fg = colors.neutral_orange },
    OldbookOrangeBold = { fg = colors.neutral_orange, bold = config.bold },
    OldbookBrown = { fg = colors.neutral_brown },
    OldbookBrownBold = { fg = colors.neutral_brown, bold = config.bold },
    OldbookRedSign = config.transparent_mode and { fg = colors.neutral_red, reverse = config.invert_signs }
        or { fg = colors.neutral_red, bg = colors.bg1, reverse = config.invert_signs },
    OldbookGreenSign = config.transparent_mode and { fg = colors.neutral_green, reverse = config.invert_signs }
        or { fg = colors.neutral_green, bg = colors.bg1, reverse = config.invert_signs },
    OldbookYellowSign = config.transparent_mode and { fg = colors.neutral_yellow, reverse = config.invert_signs }
        or { fg = colors.neutral_yellow, bg = colors.bg1, reverse = config.invert_signs },
    OldbookBlueSign = config.transparent_mode and { fg = colors.neutral_blue, reverse = config.invert_signs }
        or { fg = colors.neutral_blue, bg = colors.bg1, reverse = config.invert_signs },
    OldbookPurpleSign = config.transparent_mode and { fg = colors.neutral_purple, reverse = config.invert_signs }
        or { fg = colors.neutral_purple, bg = colors.bg1, reverse = config.invert_signs },
    OldbookAquaSign = config.transparent_mode and { fg = colors.neutral_aqua, reverse = config.invert_signs }
        or { fg = colors.neutral_aqua, bg = colors.bg1, reverse = config.invert_signs },
    OldbookOrangeSign = config.transparent_mode and { fg = colors.neutral_orange, reverse = config.invert_signs }
        or { fg = colors.neutral_orange, bg = colors.bg1, reverse = config.invert_signs },
    OldbookRedUnderline = { undercurl = config.undercurl, sp = colors.neutral_red },
    OldbookGreenUnderline = { undercurl = config.undercurl, sp = colors.neutral_green },
    OldbookYellowUnderline = { undercurl = config.undercurl, sp = colors.neutral_yellow },
    OldbookBlueUnderline = { undercurl = config.undercurl, sp = colors.neutral_blue },
    OldbookPurpleUnderline = { undercurl = config.undercurl, sp = colors.neutral_purple },
    OldbookAquaUnderline = { undercurl = config.undercurl, sp = colors.neutral_aqua },
    OldbookOrangeUnderline = { undercurl = config.undercurl, sp = colors.neutral_orange },
    Normal = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = config.transparent_mode and { fg = colors.fg1, bg = nil } or { fg = colors.fg1, bg = colors.bg1 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = colors.bg2, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
    NonText = { link = "OldbookBg2" },
    SpecialKey = { link = "OldbookFg2" },
    Visual = { bg = colors.bg2, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
    Underlined = { fg = colors.blue, underline = config.underline },
    StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg2, reverse = config.inverse },
    WinBar = { fg = colors.fg2, bg = colors.bg0 },
    WinBarNC = { fg = colors.fg1, bg = colors.bg1 },
    WinSeparator = config.transparent_mode and { fg = colors.bg2, bg = nil } or { fg = colors.bg2, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "OldbookBlueBold" },
    Title = { link = "OldbookGreenBold" },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MoreMsg = { link = "OldbookYellowBold" },
    ModeMsg = { link = "OldbookYellowBold" },
    Question = { link = "OldbookOrangeBold" },
    WarningMsg = { link = "OldbookRedBold" },
    LineNr = { fg = colors.neutral_blue },
    SignColumn = config.transparent_mode and { bg = nil } or { bg = colors.bg1 },
    Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { fg = colors.gray, bg = nil } or { fg = colors.gray, bg = colors.bg1 },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "OldbookOrange" },
    Comment = { fg = colors.green, italic = config.italic.comments },
    Todo = { fg = colors.bg0, bg = colors.yellow, bold = config.bold, italic = config.italic.comments },
    Done = { fg = colors.orange, bold = config.bold, italic = config.italic.comments },
    Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
    Statement = { link = "OldbookBlue" },
    Conditional = { link = "OldbookRed" },
    Repeat = { link = "OldbookRed" },
    Label = { link = "OldbookPurple" },
    Exception = { link = "OldbookRed" },
    Operator = { fg = colors.neutral_orange, italic = config.italic.operators },
    Keyword = { link = "OldbookBrown" },
    Identifier = { link = "OldbookBlue" },
    Function = { link = "OldbookPurple" },
    PreProc = { link = "OldbookAqua" },
    Include = { link = "OldbookGreen" },
    Define = { link = "OldbookGreen" },
    Macro = { link = "OldbookGreen" },
    PreCondit = { link = "OldbookGreen" },
    Constant = { link = "OldbookPurpleBold" },
    Character = { link = "OldbookPurple" },
    String = { fg = colors.neutral_aqua, italic = config.italic.strings },
    Boolean = { fg = colors.blue },
    Number = { fg = colors.red },
    Float = { fg = colors.red },
    Type = { link = "OldbookBrownBold" },
    StorageClass = { link = "OldbookOrange" },
    Structure = { link = "OldbookAqua" },
    Typedef = { link = "OldbookYellow" },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    DiffDelete = { bg = colors.red },
    DiffAdd = { bg = colors.green },
    DiffChange = { bg = colors.aqua },
    DiffText = { bg = colors.yellow, fg = colors.bg0 },
    SpellCap = { link = "OldbookBlueUnderline" },
    SpellBad = { link = "OldbookRedUnderline" },
    SpellLocal = { link = "OldbookAquaUnderline" },
    SpellRare = { link = "OldbookPurpleUnderline" },
    Whitespace = { fg = colors.bg2 },
    DiagnosticError = { link = "OldbookRed" },
    DiagnosticSignError = { link = "OldbookRedSign" },
    DiagnosticUnderlineError = { link = "OldbookRedUnderline" },
    DiagnosticWarn = { link = "OldbookYellow" },
    DiagnosticSignWarn = { link = "OldbookYellowSign" },
    DiagnosticUnderlineWarn = { link = "OldbookYellowUnderline" },
    DiagnosticInfo = { link = "OldbookBlue" },
    DiagnosticSignInfo = { link = "OldbookBlueSign" },
    DiagnosticUnderlineInfo = { link = "OldbookBlueUnderline" },
    DiagnosticHint = { link = "OldbookAqua" },
    DiagnosticSignHint = { link = "OldbookAquaSign" },
    DiagnosticUnderlineHint = { link = "OldbookAquaUnderline" },
    DiagnosticFloatingError = { link = "OldbookRed" },
    DiagnosticFloatingWarn = { link = "OldbookOrange" },
    DiagnosticFloatingInfo = { link = "OldbookBlue" },
    DiagnosticFloatingHint = { link = "OldbookAqua" },
    DiagnosticVirtualTextError = { link = "OldbookRed" },
    DiagnosticVirtualTextWarn = { link = "OldbookYellow" },
    DiagnosticVirtualTextInfo = { link = "OldbookBlue" },
    DiagnosticVirtualTextHint = { link = "OldbookAqua" },
    DiagnosticOk = { link = "OldbookGreenSign" },
    LspReferenceRead = { link = "OldbookYellowBold" },
    LspReferenceText = { link = "OldbookYellowBold" },
    LspReferenceWrite = { link = "OldbookOrangeBold" },
    LspCodeLens = { link = "OldbookGray" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { link = "OldbookGreen" },
    gitcommitDiscardedFile = { link = "OldbookRed" },
    GitSignsAdd = { link = "OldbookGreen" },
    GitSignsChange = { link = "OldbookAqua" },
    GitSignsDelete = { link = "OldbookRed" },
    NvimTreeSymlink = { fg = colors.neutral_aqua },
    NvimTreeRootFolder = { fg = colors.neutral_purple, bold = true },
    NvimTreeFolderIcon = { fg = colors.neutral_blue, bold = true },
    NvimTreeFileIcon = { fg = colors.light2 },
    NvimTreeExecFile = { fg = colors.neutral_green, bold = true },
    NvimTreeOpenedFile = { fg = colors.bright_red, bold = true },
    NvimTreeSpecialFile = { fg = colors.neutral_yellow, bold = true, underline = true },
    NvimTreeImageFile = { fg = colors.neutral_purple },
    NvimTreeIndentMarker = { fg = colors.dark0 },
    NvimTreeGitDirty = { fg = colors.neutral_yellow },
    NvimTreeGitStaged = { fg = colors.neutral_yellow },
    NvimTreeGitMerge = { fg = colors.neutral_purple },
    NvimTreeGitRenamed = { fg = colors.neutral_purple },
    NvimTreeGitNew = { fg = colors.neutral_yellow },
    NvimTreeGitDeleted = { fg = colors.neutral_red },
    NvimTreeWindowPicker = { bg = colors.aqua },
    debugPC = { bg = colors.blue },
    debugBreakpoint = { link = "OldbookRedSign" },
    StartifyBracket = { link = "OldbookFg1" },
    StartifyFile = { link = "OldbookFg1" },
    StartifyNumber = { link = "OldbookBlue" },
    StartifyPath = { link = "OldbookGray" },
    StartifySlash = { link = "OldbookGray" },
    StartifySection = { link = "OldbookYellow" },
    StartifySpecial = { link = "OldbookBg2" },
    StartifyHeader = { link = "OldbookOrange" },
    StartifyFooter = { link = "OldbookBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "OldbookAqua" },
    DirvishArg = { link = "OldbookYellow" },
    netrwDir = { link = "OldbookAqua" },
    netrwClassify = { link = "OldbookAqua" },
    netrwLink = { link = "OldbookGray" },
    netrwSymLink = { link = "OldbookFg1" },
    netrwExe = { link = "OldbookYellow" },
    netrwComment = { link = "OldbookGray" },
    netrwList = { link = "OldbookBlue" },
    netrwHelpCmd = { link = "OldbookAqua" },
    netrwCmdSep = { link = "OldbookFg1" },
    netrwVersion = { link = "OldbookGreen" },
    NERDTreeDir = { link = "OldbookAqua" },
    NERDTreeDirSlash = { link = "OldbookAqua" },
    NERDTreeOpenable = { link = "OldbookOrange" },
    NERDTreeClosable = { link = "OldbookOrange" },
    NERDTreeFile = { link = "OldbookFg1" },
    NERDTreeExecFile = { link = "OldbookYellow" },
    NERDTreeUp = { link = "OldbookGray" },
    NERDTreeCWD = { link = "OldbookGreen" },
    NERDTreeHelp = { link = "OldbookFg1" },
    NERDTreeToggleOn = { link = "OldbookGreen" },
    NERDTreeToggleOff = { link = "OldbookRed" },
    CocErrorSign = { link = "OldbookRedSign" },
    CocWarningSign = { link = "OldbookOrangeSign" },
    CocInfoSign = { link = "OldbookBlueSign" },
    CocHintSign = { link = "OldbookAquaSign" },
    CocErrorFloat = { link = "OldbookRed" },
    CocWarningFloat = { link = "OldbookOrange" },
    CocInfoFloat = { link = "OldbookBlue" },
    CocHintFloat = { link = "OldbookAqua" },
    CocDiagnosticsError = { link = "OldbookRed" },
    CocDiagnosticsWarning = { link = "OldbookOrange" },
    CocDiagnosticsInfo = { link = "OldbookBlue" },
    CocDiagnosticsHint = { link = "OldbookAqua" },
    CocSelectedText = { link = "OldbookRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "OldbookGray" },
    CocErrorHighlight = { link = "OldbookRedUnderline" },
    CocWarningHighlight = { link = "OldbookOrangeUnderline" },
    CocInfoHighlight = { link = "OldbookBlueUnderline" },
    CocHintHighlight = { link = "OldbookAquaUnderline" },
    TelescopeNormal = { link = "OldbookFg1" },
    TelescopeSelection = { link = "OldbookOrangeBold" },
    TelescopeSelectionCaret = { link = "OldbookRed" },
    TelescopeMultiSelection = { link = "OldbookGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "OldbookBlue" },
    TelescopePromptPrefix = { link = "OldbookRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    CmpItemAbbr = { link = "OldbookFg0" },
    CmpItemAbbrDeprecated = { link = "OldbookFg1" },
    CmpItemAbbrMatch = { link = "OldbookBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "OldbookBlueUnderline" },
    CmpItemMenu = { link = "OldbookGray" },
    CmpItemKindText = { link = "OldbookOrange" },
    CmpItemKindVariable = { link = "OldbookOrange" },
    CmpItemKindMethod = { link = "OldbookBlue" },
    CmpItemKindFunction = { link = "OldbookBlue" },
    CmpItemKindConstructor = { link = "OldbookYellow" },
    CmpItemKindUnit = { link = "OldbookBlue" },
    CmpItemKindField = { link = "OldbookBlue" },
    CmpItemKindClass = { link = "OldbookYellow" },
    CmpItemKindInterface = { link = "OldbookYellow" },
    CmpItemKindModule = { link = "OldbookBlue" },
    CmpItemKindProperty = { link = "OldbookBlue" },
    CmpItemKindValue = { link = "OldbookOrange" },
    CmpItemKindEnum = { link = "OldbookYellow" },
    CmpItemKindOperator = { link = "OldbookYellow" },
    CmpItemKindKeyword = { link = "OldbookPurple" },
    CmpItemKindEvent = { link = "OldbookPurple" },
    CmpItemKindReference = { link = "OldbookPurple" },
    CmpItemKindColor = { link = "OldbookPurple" },
    CmpItemKindSnippet = { link = "OldbookGreen" },
    CmpItemKindFile = { link = "OldbookBlue" },
    CmpItemKindFolder = { link = "OldbookBlue" },
    CmpItemKindEnumMember = { link = "OldbookAqua" },
    CmpItemKindConstant = { link = "OldbookOrange" },
    CmpItemKindStruct = { link = "OldbookYellow" },
    CmpItemKindTypeParameter = { link = "OldbookYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "OldbookOrange" },
    diffNewFile = { link = "OldbookYellow" },
    diffOldFile = { link = "OldbookOrange" },
    diffLine = { link = "OldbookBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "OldbookBlue" },
    NavicIconsModule = { link = "OldbookOrange" },
    NavicIconsNamespace = { link = "OldbookBlue" },
    NavicIconsPackage = { link = "OldbookAqua" },
    NavicIconsClass = { link = "OldbookYellow" },
    NavicIconsMethod = { link = "OldbookBlue" },
    NavicIconsProperty = { link = "OldbookAqua" },
    NavicIconsField = { link = "OldbookPurple" },
    NavicIconsConstructor = { link = "OldbookBlue" },
    NavicIconsEnum = { link = "OldbookPurple" },
    NavicIconsInterface = { link = "OldbookGreen" },
    NavicIconsFunction = { link = "OldbookBlue" },
    NavicIconsVariable = { link = "OldbookPurple" },
    NavicIconsConstant = { link = "OldbookOrange" },
    NavicIconsString = { link = "OldbookGreen" },
    NavicIconsNumber = { link = "OldbookOrange" },
    NavicIconsBoolean = { link = "OldbookOrange" },
    NavicIconsArray = { link = "OldbookOrange" },
    NavicIconsObject = { link = "OldbookOrange" },
    NavicIconsKey = { link = "OldbookAqua" },
    NavicIconsNull = { link = "OldbookOrange" },
    NavicIconsEnumMember = { link = "OldbookYellow" },
    NavicIconsStruct = { link = "OldbookPurple" },
    NavicIconsEvent = { link = "OldbookYellow" },
    NavicIconsOperator = { link = "OldbookRed" },
    NavicIconsTypeParameter = { link = "OldbookRed" },
    NavicText = { link = "OldbookWhite" },
    NavicSeparator = { link = "OldbookWhite" },
    htmlTag = { link = "OldbookAquaBold" },
    htmlEndTag = { link = "OldbookAquaBold" },
    htmlTagName = { link = "OldbookBlue" },
    htmlArg = { link = "OldbookOrange" },
    htmlTagN = { link = "OldbookFg1" },
    htmlSpecialTagName = { link = "OldbookBlue" },
    htmlLink = { fg = colors.fg2, underline = config.underline },
    htmlSpecialChar = { link = "OldbookRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, italic = true },
    xmlTag = { link = "OldbookAquaBold" },
    xmlEndTag = { link = "OldbookAquaBold" },
    xmlTagName = { link = "OldbookBlue" },
    xmlEqual = { link = "OldbookBlue" },
    docbkKeyword = { link = "OldbookAquaBold" },
    xmlDocTypeDecl = { link = "OldbookGray" },
    xmlDocTypeKeyword = { link = "OldbookPurple" },
    xmlCdataStart = { link = "OldbookGray" },
    xmlCdataCdata = { link = "OldbookPurple" },
    dtdFunction = { link = "OldbookGray" },
    dtdTagName = { link = "OldbookPurple" },
    xmlAttrib = { link = "OldbookOrange" },
    xmlProcessingDelim = { link = "OldbookGray" },
    dtdParamEntityPunct = { link = "OldbookGray" },
    dtdParamEntityDPunct = { link = "OldbookGray" },
    xmlAttribPunct = { link = "OldbookGray" },
    xmlEntity = { link = "OldbookRed" },
    xmlEntityPunct = { link = "OldbookRed" },
    clojureKeyword = { link = "OldbookBlue" },
    clojureCond = { link = "OldbookOrange" },
    clojureSpecial = { link = "OldbookOrange" },
    clojureDefine = { link = "OldbookOrange" },
    clojureFunc = { link = "OldbookYellow" },
    clojureRepeat = { link = "OldbookYellow" },
    clojureCharacter = { link = "OldbookAqua" },
    clojureStringEscape = { link = "OldbookAqua" },
    clojureException = { link = "OldbookRed" },
    clojureRegexp = { link = "OldbookAqua" },
    clojureRegexpEscape = { link = "OldbookAqua" },
    clojureRegexpCharClass = { fg = colors.fg1, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "OldbookFg1" },
    clojureAnonArg = { link = "OldbookYellow" },
    clojureVariable = { link = "OldbookBlue" },
    clojureMacro = { link = "OldbookOrange" },
    clojureMeta = { link = "OldbookYellow" },
    clojureDeref = { link = "OldbookYellow" },
    clojureQuote = { link = "OldbookYellow" },
    clojureUnquote = { link = "OldbookYellow" },
    cOperator = { link = "OldbookPurple" },
    cppOperator = { link = "OldbookPurple" },
    cStructure = { link = "OldbookOrange" },
    pythonBuiltin = { link = "OldbookOrange" },
    pythonBuiltinObj = { link = "OldbookOrange" },
    pythonBuiltinFunc = { link = "OldbookOrange" },
    pythonFunction = { link = "OldbookAqua" },
    pythonDecorator = { link = "OldbookRed" },
    pythonInclude = { link = "OldbookBlue" },
    pythonImport = { link = "OldbookBlue" },
    pythonRun = { link = "OldbookBlue" },
    pythonCoding = { link = "OldbookBlue" },
    pythonOperator = { link = "OldbookRed" },
    pythonException = { link = "OldbookRed" },
    pythonExceptions = { link = "OldbookPurple" },
    pythonBoolean = { link = "OldbookPurple" },
    pythonDot = { link = "OldbookFg1" },
    pythonConditional = { link = "OldbookRed" },
    pythonRepeat = { link = "OldbookRed" },
    pythonDottedName = { link = "OldbookGreenBold" },
    cssBraces = { link = "OldbookBlue" },
    cssFunctionName = { link = "OldbookYellow" },
    cssIdentifier = { link = "OldbookOrange" },
    cssClassName = { link = "OldbookGreen" },
    cssColor = { link = "OldbookBlue" },
    cssSelectorOp = { link = "OldbookBlue" },
    cssSelectorOp2 = { link = "OldbookBlue" },
    cssImportant = { link = "OldbookGreen" },
    cssVendor = { link = "OldbookFg1" },
    cssTextProp = { link = "OldbookAqua" },
    cssAnimationProp = { link = "OldbookAqua" },
    cssUIProp = { link = "OldbookYellow" },
    cssTransformProp = { link = "OldbookAqua" },
    cssTransitionProp = { link = "OldbookAqua" },
    cssPrintProp = { link = "OldbookAqua" },
    cssPositioningProp = { link = "OldbookYellow" },
    cssBoxProp = { link = "OldbookAqua" },
    cssFontDescriptorProp = { link = "OldbookAqua" },
    cssFlexibleBoxProp = { link = "OldbookAqua" },
    cssBorderOutlineProp = { link = "OldbookAqua" },
    cssBackgroundProp = { link = "OldbookAqua" },
    cssMarginProp = { link = "OldbookAqua" },
    cssListProp = { link = "OldbookAqua" },
    cssTableProp = { link = "OldbookAqua" },
    cssFontProp = { link = "OldbookAqua" },
    cssPaddingProp = { link = "OldbookAqua" },
    cssDimensionProp = { link = "OldbookAqua" },
    cssRenderProp = { link = "OldbookAqua" },
    cssColorProp = { link = "OldbookAqua" },
    cssGeneratedContentProp = { link = "OldbookAqua" },
    javaScriptBraces = { link = "OldbookFg1" },
    javaScriptFunction = { link = "OldbookAqua" },
    javaScriptIdentifier = { link = "OldbookRed" },
    javaScriptMember = { link = "OldbookBlue" },
    javaScriptNumber = { link = "OldbookPurple" },
    javaScriptNull = { link = "OldbookPurple" },
    javaScriptParens = { link = "OldbookFg1" },
    typescriptReserved = { link = "OldbookAqua" },
    typescriptLabel = { link = "OldbookAqua" },
    typescriptFuncKeyword = { link = "OldbookAqua" },
    typescriptIdentifier = { link = "OldbookOrange" },
    typescriptBraces = { link = "OldbookFg1" },
    typescriptEndColons = { link = "OldbookFg1" },
    typescriptDOMObjects = { link = "OldbookFg1" },
    typescriptAjaxMethods = { link = "OldbookFg1" },
    typescriptLogicSymbols = { link = "OldbookFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "OldbookFg1" },
    typescriptParens = { link = "OldbookFg1" },
    typescriptOpSymbols = { link = "OldbookFg1" },
    typescriptHtmlElemProperties = { link = "OldbookFg1" },
    typescriptNull = { link = "OldbookPurple" },
    typescriptInterpolationDelimiter = { link = "OldbookAqua" },
    purescriptModuleKeyword = { link = "OldbookAqua" },
    purescriptModuleName = { link = "OldbookFg1" },
    purescriptWhere = { link = "OldbookAqua" },
    purescriptDelimiter = { link = "OldbookFg2" },
    purescriptType = { link = "OldbookFg1" },
    purescriptImportKeyword = { link = "OldbookAqua" },
    purescriptHidingKeyword = { link = "OldbookAqua" },
    purescriptAsKeyword = { link = "OldbookAqua" },
    purescriptStructure = { link = "OldbookAqua" },
    purescriptOperator = { link = "OldbookBlue" },
    purescriptTypeVar = { link = "OldbookFg1" },
    purescriptConstructor = { link = "OldbookFg1" },
    purescriptFunction = { link = "OldbookFg1" },
    purescriptConditional = { link = "OldbookOrange" },
    purescriptBacktick = { link = "OldbookOrange" },
    coffeeExtendedOp = { link = "OldbookFg1" },
    coffeeSpecialOp = { link = "OldbookFg1" },
    coffeeCurly = { link = "OldbookOrange" },
    coffeeParen = { link = "OldbookFg1" },
    coffeeBracket = { link = "OldbookOrange" },
    rubyStringDelimiter = { link = "OldbookGreen" },
    rubyInterpolationDelimiter = { link = "OldbookAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "OldbookRed" },
    objcDirective = { link = "OldbookBlue" },
    goDirective = { link = "OldbookAqua" },
    goConstants = { link = "OldbookPurple" },
    goDeclaration = { link = "OldbookRed" },
    goDeclType = { link = "OldbookBlue" },
    goBuiltins = { link = "OldbookOrange" },
    luaIn = { link = "OldbookRed" },
    luaFunction = { link = "OldbookAqua" },
    luaTable = { link = "OldbookOrange" },
    moonSpecialOp = { link = "OldbookFg1" },
    moonExtendedOp = { link = "OldbookFg1" },
    moonFunction = { link = "OldbookFg1" },
    moonObject = { link = "OldbookYellow" },
    javaAnnotation = { link = "OldbookBlue" },
    javaDocTags = { link = "OldbookAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "OldbookFg1" },
    javaParen1 = { link = "OldbookFg1" },
    javaParen2 = { link = "OldbookFg1" },
    javaParen3 = { link = "OldbookFg1" },
    javaParen4 = { link = "OldbookFg1" },
    javaParen5 = { link = "OldbookFg1" },
    javaOperator = { link = "OldbookOrange" },
    javaVarArg = { link = "OldbookGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "OldbookGreen" },
    elixirInterpolationDelimiter = { link = "OldbookAqua" },
    elixirModuleDeclaration = { link = "OldbookYellow" },
    scalaNameDefinition = { link = "OldbookFg1" },
    scalaCaseFollowing = { link = "OldbookFg1" },
    scalaCapitalWord = { link = "OldbookFg1" },
    scalaTypeExtension = { link = "OldbookFg1" },
    scalaKeyword = { link = "OldbookRed" },
    scalaKeywordModifier = { link = "OldbookRed" },
    scalaSpecial = { link = "OldbookAqua" },
    scalaOperator = { link = "OldbookFg1" },
    scalaTypeDeclaration = { link = "OldbookYellow" },
    scalaTypeTypePostDeclaration = { link = "OldbookYellow" },
    scalaInstanceDeclaration = { link = "OldbookFg1" },
    scalaInterpolation = { link = "OldbookAqua" },
    markdownItalic = { fg = colors.fg1, italic = true },
    markdownBold = { fg = colors.fg1, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg1, bold = config.bold, italic = true },
    markdownH1 = { link = "OldbookGreenBold" },
    markdownH2 = { link = "OldbookGreenBold" },
    markdownH3 = { link = "OldbookYellowBold" },
    markdownH4 = { link = "OldbookYellowBold" },
    markdownH5 = { link = "OldbookYellow" },
    markdownH6 = { link = "OldbookYellow" },
    markdownCode = { link = "OldbookAqua" },
    markdownCodeBlock = { link = "OldbookAqua" },
    markdownCodeDelimiter = { link = "OldbookAqua" },
    markdownBlockquote = { link = "OldbookGray" },
    markdownListMarker = { link = "OldbookGray" },
    markdownOrderedListMarker = { link = "OldbookGray" },
    markdownRule = { link = "OldbookGray" },
    markdownHeadingRule = { link = "OldbookGray" },
    markdownUrlDelimiter = { link = "OldbookFg1" },
    markdownLinkDelimiter = { link = "OldbookFg1" },
    markdownLinkTextDelimiter = { link = "OldbookFg1" },
    markdownHeadingDelimiter = { link = "OldbookOrange" },
    markdownUrl = { link = "OldbookPurple" },
    markdownUrlTitleDelimiter = { link = "OldbookGreen" },
    markdownLinkText = { fg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "OldbookBlue" },
    haskellIdentifier = { link = "OldbookAqua" },
    haskellSeparator = { link = "OldbookFg2" },
    haskellDelimiter = { link = "OldbookOrange" },
    haskellOperators = { link = "OldbookPurple" },
    haskellBacktick = { link = "OldbookOrange" },
    haskellStatement = { link = "OldbookPurple" },
    haskellConditional = { link = "OldbookPurple" },
    haskellLet = { link = "OldbookRed" },
    haskellDefault = { link = "OldbookRed" },
    haskellWhere = { link = "OldbookRed" },
    haskellBottom = { link = "OldbookRedBold" },
    haskellImportKeywords = { link = "OldbookPurpleBold" },
    haskellDeclKeyword = { link = "OldbookOrange" },
    haskellDecl = { link = "OldbookOrange" },
    haskellDeriving = { link = "OldbookPurple" },
    haskellAssocType = { link = "OldbookAqua" },
    haskellNumber = { link = "OldbookAqua" },
    haskellPragma = { link = "OldbookRedBold" },
    haskellTH = { link = "OldbookAquaBold" },
    haskellForeignKeywords = { link = "OldbookGreen" },
    haskellKeyword = { link = "OldbookRed" },
    haskellFloat = { link = "OldbookAqua" },
    haskellInfix = { link = "OldbookPurple" },
    haskellQuote = { link = "OldbookGreenBold" },
    haskellShebang = { link = "OldbookYellowBold" },
    haskellLiquid = { link = "OldbookPurpleBold" },
    haskellQuasiQuoted = { link = "OldbookBlueBold" },
    haskellRecursiveDo = { link = "OldbookPurple" },
    haskellQuotedType = { link = "OldbookRed" },
    haskellPreProc = { link = "OldbookFg2" },
    haskellTypeRoles = { link = "OldbookRedBold" },
    haskellTypeForall = { link = "OldbookRed" },
    haskellPatternKeyword = { link = "OldbookBlue" },
    jsonKeyword = { link = "OldbookGreen" },
    jsonQuote = { link = "OldbookGreen" },
    jsonBraces = { link = "OldbookFg1" },
    jsonString = { link = "OldbookFg1" },
    mailQuoted1 = { link = "OldbookAqua" },
    mailQuoted2 = { link = "OldbookPurple" },
    mailQuoted3 = { link = "OldbookYellow" },
    mailQuoted4 = { link = "OldbookGreen" },
    mailQuoted5 = { link = "OldbookRed" },
    mailQuoted6 = { link = "OldbookOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "OldbookFg1" },
    csEndColon = { link = "OldbookFg1" },
    csLogicSymbols = { link = "OldbookFg1" },
    csParens = { link = "OldbookFg1" },
    csOpSymbols = { link = "OldbookFg1" },
    csInterpolationDelimiter = { link = "OldbookFg1" },
    csInterpolationAlignDel = { link = "OldbookAquaBold" },
    csInterpolationFormat = { link = "OldbookAqua" },
    csInterpolationFormatDel = { link = "OldbookAquaBold" },
    rustSigil = { link = "OldbookOrange" },
    rustEscape = { link = "OldbookAqua" },
    rustStringContinuation = { link = "OldbookAqua" },
    rustEnum = { link = "OldbookAqua" },
    rustStructure = { link = "OldbookAqua" },
    rustModPathSep = { link = "OldbookFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "OldbookAqua" },
    ocamlOperator = { link = "OldbookFg1" },
    ocamlKeyChar = { link = "OldbookOrange" },
    ocamlArrow = { link = "OldbookOrange" },
    ocamlInfixOpKeyword = { link = "OldbookRed" },
    ocamlConstructor = { link = "OldbookOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "OldbookFg1" },
    LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "OldbookFg1" },
    LspSagaAutoPreview = { link = "OldbookOrange" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "OldbookAqua" },
    LspSagaDefPreviewBorder = { link = "OldbookBlue" },
    LspSagaHoverBorder = { link = "OldbookOrange" },
    LspSagaRenameBorder = { link = "OldbookBlue" },
    LspSagaDiagnosticSource = { link = "OldbookOrange" },
    LspSagaDiagnosticBorder = { link = "OldbookPurple" },
    LspSagaDiagnosticHeader = { link = "OldbookGreen" },
    LspSagaSignatureHelpBorder = { link = "OldbookGreen" },
    SagaShadow = { link = "OldbookBg0" },
    DashboardShortCut = { link = "OldbookOrange" },
    DashboardHeader = { link = "OldbookAqua" },
    DashboardCenter = { link = "OldbookYellow" },
    DashboardFooter = { fg = colors.purple, italic = true },
    MasonHighlight = { link = "OldbookAqua" },
    MasonHighlightBlock = { fg = colors.bg0, bg = colors.blue },
    MasonHighlightBlockBold = { fg = colors.bg0, bg = colors.blue, bold = true },
    MasonHighlightSecondary = { fg = colors.yellow },
    MasonHighlightBlockSecondary = { fg = colors.bg0, bg = colors.yellow },
    MasonHighlightBlockBoldSecondary = { fg = colors.bg0, bg = colors.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { fg = colors.fg2 },
    MasonMutedBlock = { fg = colors.bg0, bg = colors.fg2 },
    MasonMutedBlockBold = { fg = colors.bg0, bg = colors.fg2, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "OldbookFg1" },
    CarbonExe = { link = "OldbookYellow" },
    CarbonSymlink = { link = "OldbookAqua" },
    CarbonBrokenSymlink = { link = "OldbookRed" },
    CarbonIndicator = { link = "OldbookGray" },
    CarbonDanger = { link = "OldbookRed" },
    CarbonPending = { link = "OldbookYellow" },
    NoiceCursor = { link = "TermCursor" },
    NotifyDEBUGBorder = { link = "OldbookBlue" },
    NotifyDEBUGIcon = { link = "OldbookBlue" },
    NotifyDEBUGTitle = { link = "OldbookBlue" },
    NotifyERRORBorder = { link = "OldbookRed" },
    NotifyERRORIcon = { link = "OldbookRed" },
    NotifyERRORTitle = { link = "OldbookRed" },
    NotifyINFOBorder = { link = "OldbookAqua" },
    NotifyINFOIcon = { link = "OldbookAqua" },
    NotifyINFOTitle = { link = "OldbookAqua" },
    NotifyTRACEBorder = { link = "OldbookGreen" },
    NotifyTRACEIcon = { link = "OldbookGreen" },
    NotifyTRACETitle = { link = "OldbookGreen" },
    NotifyWARNBorder = { link = "OldbookYellow" },
    NotifyWARNIcon = { link = "OldbookYellow" },
    NotifyWARNTitle = { link = "OldbookYellow" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { fg = colors.red },
    TSRainbowOrange = { fg = colors.orange },
    TSRainbowYellow = { fg = colors.yellow },
    TSRainbowGreen = { fg = colors.green },
    TSRainbowBlue = { fg = colors.blue },
    TSRainbowViolet = { fg = colors.purple },
    TSRainbowCyan = { fg = colors.cyan },
    DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
    DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { link = "OldbookYellow" },
    DapUIBreakpointsDisabledLine = { link = "OldbookGray" },
    DapUIBreakpointsInfo = { link = "OldbookAqua" },
    DapUIBreakpointsLine = { link = "OldbookYellow" },
    DapUIBreakpointsPath = { link = "OldbookBlue" },
    DapUICurrentFrameName = { link = "OldbookPurple" },
    DapUIDecoration = { link = "OldbookPurple" },
    DapUIEndofBuffer = { link = "OldbookBg2" },
    DapUIFloatBorder = { link = "OldbookAqua" },
    DapUILineNumber = { link = "OldbookYellow" },
    DapUIModifiedValue = { link = "OldbookRed" },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { link = "OldbookBlue" },
    DapUISource = { link = "OldbookFg1" },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    DapUIStoppedThread = { link = "OldbookBlue" },
    DapUIThread = { link = "OldbookBlue" },
    DapUIType = { link = "OldbookOrange" },
    DapUIUnavailable = { link = "OldbookGray" },
    DapUIWatchesEmpty = { link = "OldbookGray" },
    DapUIWatchesError = { link = "OldbookRed" },
    DapUIWatchesValue = { link = "OldbookYellow" },
    DapUIWinSelect = { link = "OldbookYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "OldbookGreenBold" },
    DiffviewFilePanelInsertions = { link = "OldbookGreenBold" },
    DiffviewFilePanelDeletions = { link = "OldbookRedBold" },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { bg = "NONE", fg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.operator"] = { link = "OldbookRed" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "OldbookFg1" },
    ["@variable.builtin"] = { link = "Special" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@namespace"] = { link = "OldbookFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "OldbookFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = colors.purple, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.fg0, bg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = {}, -- do not overwrite comments
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
  }

  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

---@param config OldbookConfig?
Oldbook.setup = function(config)
  Oldbook.config = vim.tbl_deep_extend("force", Oldbook.config, config or {})
end

--- main load function
Oldbook.load = function()
  -- reset colors
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "oldbook"
  vim.o.termguicolors = true

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    vim.api.nvim_set_hl(0, group, settings)
  end
end

return Oldbook
